version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:266735821233:task-definition/test-td:1"  # ECS Task Definition ARN
        LoadBalancerInfo:
          ContainerName: "test-cont"  # Container name in ECS Task Definition
          ContainerPort: 5000  # Port the container listens
