version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:463470956417:task-definition/my_bg_td:2"  # ECS Task Definition ARN
        LoadBalancerInfo:
          ContainerName: "test-cont"  # Container name in ECS Task Definition
          ContainerPort: 5000  # Port the container listens
